feat: Implement process member bundle request queue
relaycorp/veraid-authority pull request #112
Opened 2023-04-21 07:52 UTC by levansuper

closes: #107

2023-04-21 09:11 UTC, gnarea commented on src/backgroundQueue/sinks/example.sink.ts
> +  options.logger.info({ event: event.toJSON() }, 'Event processed');
Make sure the final event log doesn't include the whole event -- just the few things we'd need to identify the event whilst troubleshooting.

2023-04-23 21:14 UTC, gnarea requested changes

2023-04-23 21:14 UTC, gnarea commented on src/backgroundQueue/sinks/memberBundleRequestTrigger.sink.spec.ts
We should also test the case where there are no requests to process (no event should be emitted, no DB record deleted).

2023-04-23 21:14 UTC, gnarea commented on src/backgroundQueue/sinks/memberBundleRequestTrigger.sink.spec.ts
> +    expect(publishedEvents).toHaveLength(1);
This seems to be outside the scope of this test, and is already tested above.

2023-04-23 21:14 UTC, gnarea commented on src/backgroundQueue/sinks/memberBundleRequestTrigger.sink.spec.ts
> +      memberBundleStartDate: addSeconds(addDays(new Date(), BUNDLE_REQUEST_DATE_RANGE), 1),
A 1-second difference is too small, so this is very likely to be a flaky test. I've been bitten by this too many times on CI, where performance is highly unpredictable 😬 

Let's increase to something like 5 or 10 seconds, which is still a negligible number considering where's dealing with days.

2023-04-24 07:16 UTC, levansuper commented on src/backgroundQueue/sinks/memberBundleRequestTrigger.sink.ts
> +  options.logger.info({ eventId: event.id, eventType: event.type }, 'Triggering bundle request');
I think we need to log eventId and eventType to identify the event.

2023-04-24 10:21 UTC, merged