feat: Implement get org route
relaycorp/veraid-authority pull request #56
Opened 2023-03-21 17:50 UTC by levansuper

# What kind of change does this PR introduce?
 

# What is the current behavior?
 

# What is the new behavior (if this is a feature change)?

# Other information

2023-03-21 18:15 UTC, gnarea requested changes
Thanks! Nearly there

2023-03-21 18:15 UTC, gnarea commented on src/services/routes/org.routes.spec.ts
> +      } as const;
If we use `as const` here, we're creating a new type, which we don't want to do. Instead, we should explicitly set the type of this variable (`SuccessfulResult<Org...>`).

2023-03-21 18:15 UTC, gnarea commented on src/services/routes/org.routes.spec.ts
> +    test('Malformed name should resolve into not found status', async () => {
I don't think we need to test the malformed case here. What difference does it make?

2023-03-22 12:47 UTC, levansuper commented on src/services/routes/org.routes.spec.ts
> +    test('Malformed name should resolve into not found status', async () => {
the only difference is in the input. The code behaves the same way so I think it's redundant

2023-03-22 12:52 UTC, gnarea approved these changes
Thanks! 🚀

2023-03-22 14:19 UTC, merged