feat: Implement member update
relaycorp/veraid-authority pull request #71
Opened 2023-04-01 17:03 UTC by levansuper

# What kind of change does this PR introduce?
 

# What is the current behavior?
 

# What is the new behavior (if this is a feature change)?

# Other information

2023-04-03 10:23 UTC, gnarea requested changes

2023-04-03 10:23 UTC, gnarea commented on src/member.ts
> +    await memberModel.findByIdAndUpdate(memberId, { ...memberData, role });
Does this work when `memberData.role` isn't set?

2023-04-03 10:23 UTC, gnarea commented on src/member.ts
> +  const role = memberData.role && ROLE_MAPPING[memberData.role];
```suggestion
  const role = memberData.role ?? ROLE_MAPPING[memberData.role];
```

That way, `role` type becomes `MemberRole | null`. (If I'm not mistaken, right now it's `MemberRole | false`)

2023-04-03 10:23 UTC, gnarea commented on src/member.spec.ts
> +    test('Valid should be updated', async () => {
This is testing the scenario where all the fields are set, but I think the opposite (nothing is changed) is also useful.

2023-04-03 10:23 UTC, gnarea commented on src/services/routes/member.routes.spec.ts
> +    test.each(memberSchemaRoles)('Role %s should be allowed', async (role: MemberSchemaRole) => {
I'm not sure this test is useful.

2023-04-03 20:21 UTC, levansuper commented on src/services/routes/member.routes.spec.ts
> +    test.each(memberSchemaRoles)('Role %s should be allowed', async (role: MemberSchemaRole) => {
This tests the role enum in the schema

2023-04-03 21:51 UTC, gnarea requested changes

2023-04-04 13:38 UTC, gnarea requested changes

2023-04-04 13:38 UTC, gnarea commented on src/models/Member.model.ts
>    public name?: string;
This type is `string | undefined`, which is wrong. It should be `string | null`:

```suggestion
  public name!: string | null;
```

2023-04-04 14:07 UTC, gnarea approved these changes
Thanks!

2023-04-04 14:16 UTC, merged